export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const SHOW_REQUEST_FORM = "SHOW_REQUEST_FORM";
export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const SHOW_ORDER_SUCCESS_MESSAGE = "SHOW_ORDER_SUCCESS_MESSAGE";
export const RESET_PAGE = "RESET_PAGE"