const initialState = {
  showHero: true,
  products: [],
  showRequestForm: false,
  task: { products: [] },
  taskID: null,
  message: "",
  showLogin: false,
  showRegister: false,
  authenticated: false,
  userEmail: undefined,
  fullName: undefined,
  phone: undefined,
  userID: undefined,
  showHelpMap: false,
  requests: [],
  requesterAddress: '',
  position: {lat: null, lng: null},
  showMarkerWindow: false,
  claimed_tasks: [],
  created_tasks: [],
  profile: {},
};

export default initialState;
